import { v4 as uuidv4 } from "uuid";

export function createManifests() {

  return {
    bpManifest: {
      format_version: 2,
      header: {
        name: "Generated Addon",
        description: "Generated by Minecraft Addon Studio",
        uuid: uuidv4(),
        version: [1, 0, 0],
        min_engine_version: [1, 21, 0]
      },
      modules: [
        {
          type: "data",
          uuid: uuidv4(),
          version: [1, 0, 0]
        }
      ]
    },

    rpManifest: {
      format_version: 2,
      header: {
        name: "Generated Addon RP",
        description: "Generated by Minecraft Addon Studio",
        uuid: uuidv4(),
        version: [1, 0, 0]
      },
      modules: [
        {
          type: "resources",
          uuid: uuidv4(),
          version: [1, 0, 0]
        }
      ]
    }
  };

}